version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"